version: 2.0
jobs:
  build:
    environment:
      - AWS_ACCESS_KEY_ID: "XXXX"
      - AWS_SECRET_ACCESS_KEY: "XXXX"
      - AWS_S3_BUCKET: "XXXX"
      - AWS_S3_REGION: "XXXX"
      - MIX_ENV: "test"
    docker:
      - image: circleci/elixir:1.4.2
      - image: postgres:9.4.1
        env:
          - POSTGRES_USER=ubuntu
    working_directory: ~/firestorm
    steps:
      - type: checkout
      - run:
          name: Install PhantomJS Dependencies
          command: |
            [ -f /usr/local/bin/phantomjs ] || sudo apt-get update
            [ -f /usr/local/bin/phantomjs ] || sudo apt-get install -y fontconfig wget
      - run:
          name: Install PhantomJS
          command: |
            [ -f /usr/local/bin/phantomjs ] || wget -O /tmp/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            [ -f /usr/local/bin/phantomjs ] || tar -xjf /tmp/phantomjs.tar.bz2 -C /tmp
            [ -f /usr/local/bin/phantomjs ] || sudo mv /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get --only test
      - run: mix test
